version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=cloudformation
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
