name: GitHub Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
      - name: Run Unit tests
        env:
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
        run: |
          docker-compose -f fake-service.yaml up -d
          make test
