name: GitHub Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up golang
        uses: actions/setup-go@v2
      - name: Run Unit tests
        env:
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
          AWS_EC2_METADATA_DISABLED: true
          AWS_REGION: ap-northeast-1
        run: |
          docker-compose -f scripts/fake-service.yaml up -d
          scripts/wait-for.sh localhost:4566 -t 300 -- echo "localstack up"
          while curl -s http://localhost:4566/health | grep -v "\"cloudformation\": \"running\""; do
              printf 'awsmock not up\n'
              sleep 10s
          done
          mkdir build
          aws cloudformation create-stack --endpoint-url http://localhost:4566 --stack-name myteststack --template-body file://scripts/mock-s3-cfn-template.yaml > build/create-stack-result.json
          cat build/create-stack-result.json
          make test
